<section>
    <header>
        <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100">
            {{ __('Avatar') }}
        </h2>

        <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
            {{ __("Update your account's profile Avatar") }}
        </p>

    </header>
    <img class="rounded-full w-20 h-20 mt-4" src="{{"/storage/$user->avatar"}}" alt="Avatar" />

    <form action="{{ route('profile.avatar.ai') }}" class="mt-2 space-y-6"  method="post">
    @csrf
        <div class="flex items-center gap-4">
            <x-primary-button>{{ __('Generate Ai Avatar') }}</x-primary-button>

            @if (session('status') === 'avatar-generated')
                <p
                    x-data="{ show: true }"
                    x-show="show"
                    x-transition
                    x-init="setTimeout(() => show = false, 2000)"
                    class="text-sm text-gray-600 dark:text-gray-400"
                >{{ __('Avatar Generated By AI.') }}</p>
            @endif
        </div>

    </form>

    <form method="post" action="{{ route('profile.avatar') }}" class="mt-2 space-y-6" enctype="multipart/form-data">
        @csrf
        @method('patch')

        <div>
            {{-- <x-input-label for="avatar" :value="__('Avatar')" /> --}}
            <x-text-input id="avatar" name="avatar" type="file" class="mt-0 block w-50" :value="old('avatar', $user->avatar)"  autofocus autocomplete="name" />
            <x-input-error class="mt-2" :messages="$errors->get('avatar')" />
        </div>

    

        <div class="flex items-center gap-4">
            <x-primary-button>{{ __('Save') }}</x-primary-button>

            @if (session('status') === 'avatar-updated')
                <p
                    x-data="{ show: true }"
                    x-show="show"
                    x-transition
                    x-init="setTimeout(() => show = false, 2000)"
                    class="text-sm text-gray-600 dark:text-gray-400"
                >{{ __('Saved.') }}</p>
            @endif
        </div>
    </form>
</section>
